name: Sakila CI/CD

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.25"

      - name: Install Dependencies
        run: go mod download

      - name: Test Go App
        run: go test

  fake-build:
    name: Build only
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.25"

      - name: Install Dependencies
        run: go mod download

      - name: Build Go App
        env:
          CGO_ENABLED: 0
          GOOS: linux
        run: go build

  build:
    name: Build & Push to GHCR
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: ["test", "fake-build"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (latest + commit-sha)
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/hikawi/sakila:latest
            ghcr.io/hikawi/sakila:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to VPS
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: ["build"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            scripts

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script_path: scripts/deploy.sh
