name: Sakila CI/CD

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      publish:
        required: false
        default: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.25"
          cache-dependency-path: ${{ inputs.service }}/go.sum

      - name: Install Dependencies
        run: go mod download
        working-directory: ${{ inputs.service }}

      - name: Test Go App
        run: go test
        working-directory: ${{ inputs.service }}

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: ["test"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.25"
          cache-dependency-path: ${{ inputs.service }}/go.sum

      - name: Install Dependencies
        run: go mod download
        working-directory: ${{ inputs.service }}

      - name: Build Go App
        env:
          CGO_ENABLED: 0
          GOOS: linux
          ldflags: -w -s
        run: go build
        working-directory: ${{ inputs.service }}

  publish:
    name: Publish to GHCR
    if: inputs.publish
    needs: ["test", "build"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.service }}
          push: true
          tags: |
            ghcr.io/hikawi/sakila:${{ inputs.service }}
